//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceJob
    {
        public int JobID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Status { get; set; }
        public string Comment { get; set; }
        public Nullable<int> TechnicianID { get; set; }
        public Nullable<int> ClientID { get; set; }
    
        public virtual Technician Technician { get; set; }
    }
}
